Poppy/app-platform-complete.json
Poppy/app-platform-minimal.json

Before the release app versions should be updated.
- increment applications versions

FIX: increment applications versions

---

Poppy/app-edge-complete.json
Poppy/app-platform-complete.json
Poppy/app-platform-minimal.json

There is an application dependencies issue.
- update dependencies

FIX: fix application dependencies

---

Poppy/app-edge-complete.json
Poppy/app-platform-complete.json
Poppy/install.json
Poppy/mds/complete/mod-data-export-spring-3.1.0.json
Poppy/mds/complete/mod-entities-links-2.1.0.json
Poppy/mds/complete/mod-pubsub-2.12.0.json
Poppy/mds/complete/mod-remote-storage-3.1.0.json
Poppy/mds/complete/mod-search-3.1.0.json

[APPDESCRIP-2](https://issues.folio.org/browse/APPDESCRIP-2)
Since several modules were released with system user features application descriptors should be updated. A tag should be created.
- update modules versions
- update app descriptors versions
- update custom MD
- update install.json file

APPDESCRIP-2: update application descriptors

---

Poppy/app-edge-complete.json
Poppy/app-platform-complete.json
Poppy/app-platform-minimal.json
Poppy/mds/minimal/mod-roles-keycloak-1.0.1.json
Poppy/mds/minimal/mod-users-keycloak-1.0.1.json

Update with latest keycloak related modules

Update apps for PoppyGA.3

---

Poppy/mds/complete/mod-consortia-keycloak-1.0.0.json

`mod-consortia-keycloak' should be actualized.
- add missing permissions
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
- Are the Rally stories under active development?
- Do PRs exist for these changes?
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the folio-testing
environment. Communication is paramount if that is to be achieved, especially as the number of inter-module and
inter-team dependencies increase.
While …

FIX: add missing interface

---

Poppy/app-platform-complete.json
Poppy/app-platform-minimal.json

This should have been part of PR #13 but that idiot @zburke missed that requirement.

bump app-platform-minimal version to 0.0.10

---

Poppy/app-edge-complete.json
Poppy/app-platform-complete.json

Fix descriptors for poppy csp1

APPDESCRIP-5: fix descriptors for poppy csp1

---

Quesnelia/app-platform-minimal.json
Quesnelia/mds/minimal/folio_authorization-roles-1.3.1.json
Quesnelia/mds/minimal/folio_stripes-core-10.1.1.json

There are validation error with current Q release. 
- update MD and AD in Q release

update AD and MD for Q release

---

Quesnelia/app-edge-complete.json

Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
- Are the Rally stories under active development?
- Do PRs exist for these changes?
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the folio-testing
environment. Communication is paramount if that is to be achieved, especially as the number of inter-module and
inter-team dependencies increase.
While it's helpful for reviewers to help identify potential problems, ensuring …

add edge-encip-1.9.2 for Quesnelia

---

Poppy/erm-usage.json
Quesnelia/erm-usage.json
Quesnelia/mds/complete/mod-erm-usage-4.7.0.json

Add application descriptors for ERM Usage modules
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
- Are the Rally stories under active development?
- Do PRs exist for these changes?
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the folio-testing
environment. Communication is paramount if that is to be achieved, especially as the number of inter-module and
inter-team dependencies increase.
While it's helpful for …

EUREKA-60: add application descriptors for ERM Usage modules

---

Quesnelia/app-platform-complete.json
Quesnelia/mds/complete/mod-organizations-1.9.0.json

https://folio-org.atlassian.net/browse/EUREKA-94
- define missed permissions in custom MD for mod-organizations

EUREKA-94: add custom md for mod-organizations with missed permission

---

Poppy/app-platform-complete.json
Poppy/app-platform-minimal.json
Poppy/install.json
Poppy/mds/complete/mod-agreements-6.0.3.json
Poppy/mds/complete/mod-finance-4.8.1.json

https://folio-org.atlassian.net/browse/APPDESCRIP-21
Update application-descriptors to the latest module versions for Poppy CSP 5
- update install.json
- update application descriptros
- update custom module descritptors

APPDESCRIP-21: update Poppy release to SP5 version

---

Poppy/app-edge-complete.json
Poppy/app-edge-locate.json
Poppy/app-erm-usage.json
Poppy/app-platform-complete.json
Poppy/app-platform-minimal.json

Update application versions after updating MD for Poppy SP5
- update app versions

APPDESCRIP-21: update application versions

---

Quesnelia/app-dcb.json
Quesnelia/app-platform-complete.json

Exclude mod-dcb and mod-circulation-item modules from app-platform-complete since they are moved to app-dcb
Related PR: https://github.com/folio-org/app-dcb/pull/1
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
- Are the Rally stories under active development?
- Do PRs exist for these changes?
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the folio-testing
environment. Communication is paramount if that is to be …

APPDESCRIP-26: move mod-dcb and mod-circulation-item modules to app-dcb

---

Quesnelia/app-platform-minimal.json

Wrong version of app-platform-minimal must be bumped
- fix application version

fix app-platform-minimal version

---

Quesnelia/app-consortia.json
Quesnelia/app-edge-complete.json
Quesnelia/app-platform-complete.json
Quesnelia/app-platform-minimal.json
Quesnelia/install.json
Quesnelia/mds/complete/folio_users-10.1.2.json
README.md

https://folio-org.atlassian.net/browse/APPDESCRIP-29
Update application-descriptors for Eureka platform for Quesnelia SP4
- update module versions
- update application versions

APPDESCRIP-29: update Quesnelia SP4

---

Quesnelia/app-platform-complete.json

https://folio-org.atlassian.net/browse/APPDESCRIP-29

APPDESCRIP-29: fix md

---

Quesnelia/app-edge-complete.json
Quesnelia/app-platform-complete.json
Quesnelia/install.json
Quesnelia/mds/complete/mod-search-3.2.7.json

https://folio-org.atlassian.net/browse/APPDESCRIP-30

APPDESCRIP-30: update module versions to QCSP5

---

Quesnelia/app-platform-complete.json
Quesnelia/app-platform-minimal.json
Quesnelia/install.json
Quesnelia/mds/minimal/folio_stripes-core-10.1.2.json

https://folio-org.atlassian.net/browse/EUREKA-578

APPDESCRIP-33: update module versions to QCSP6

---

Quesnelia/app-platform-complete.json
Quesnelia/install.json

https://folio-org.atlassian.net/browse/APPDESCRIP-36

APPDESCRIP-36: update module versions to QCSP7

---

Quesnelia/app-platform-complete.json
Quesnelia/app-platform-minimal.json
Quesnelia/install.json
Quesnelia/mds/minimal/folio_stripes-core-10.1.4.json

update app description for Q to CSP8
https://folio-org.atlassian.net/browse/APPDESCRIP-38

APPDESCRIP-38: update app description for Q to CSP8

---

Quesnelia/app-edge-complete.json
Quesnelia/app-platform-complete.json
Quesnelia/app-platform-minimal.json
Quesnelia/install.json

- Update Application Descriptors to the Quesnelia SP9
[APPDESCRIP-41](https://folio-org.atlassian.net/browse/APPDESCRIP-41)

APPDESCRIP-41: Update Application Descriptors for Quesnelia CSP#9
